# Generated by Django 5.2.7 on 2026-02-10 22:17

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('laptops', 'Laptops'), ('laptop-chargers', 'Laptop Chargers'), ('wifi-routers', 'WiFi Routers'), ('external-drives', 'External Drives')], max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('UK Used', 'UK Used')], default='UK Used', max_length=20)),
                ('brand', models.CharField(choices=[('apple', 'Apple (MacBook)'), ('dell', 'Dell'), ('hp', 'HP (Hewlett-Packard)'), ('lenovo', 'Lenovo'), ('asus', 'ASUS'), ('acer', 'Acer'), ('microsoft', 'Microsoft (Surface)'), ('samsung', 'Samsung'), ('msi', 'MSI (Micro-Star International)'), ('razer', 'Razer'), ('lg', 'LG (Gram)'), ('toshiba', 'Toshiba / Dynabook'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('accessories', 'Accessories')], default='accessories', max_length=40)),
                ('main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('specifications', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('product_title', models.CharField(blank=True, max_length=200)),
                ('specs', models.TextField(blank=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compare_at', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('slot', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_items', to='store.product')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_items', to='store.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CountdownDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=300)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countdown_deals', to='store.product')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='store_produ_created_0fbdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='hotitem',
            index=models.Index(fields=['active', 'position'], name='store_hotit_active_41afc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='heroitem',
            constraint=models.UniqueConstraint(fields=('position',), name='unique_hero_position'),
        ),
        migrations.AddConstraint(
            model_name='heroitem',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_product_in_hero'),
        ),
        migrations.AddIndex(
            model_name='countdowndeal',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='store_count_active_c260ee_idx'),
        ),
    ]
