# Generated by Django 5.2.7 on 2026-06-12 11:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


GHANA_REGIONS = [
    ("Ahafo", "ahafo"),
    ("Ashanti", "ashanti"),
    ("Bono", "bono"),
    ("Bono East", "bono-east"),
    ("Central", "central"),
    ("Eastern", "eastern"),
    ("Greater Accra", "greater-accra"),
    ("North East", "north-east"),
    ("Northern", "northern"),
    ("Oti", "oti"),
    ("Savannah", "savannah"),
    ("Upper East", "upper-east"),
    ("Upper West", "upper-west"),
    ("Volta", "volta"),
    ("Western", "western"),
    ("Western North", "western-north"),
]


def seed_shipping_regions_and_charge(apps, schema_editor):
    ShippingRegion = apps.get_model("store", "ShippingRegion")
    CheckoutCharge = apps.get_model("store", "CheckoutCharge")

    for position, (name, slug) in enumerate(GHANA_REGIONS, start=1):
        ShippingRegion.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "position": position, "active": True},
        )

    CheckoutCharge.objects.get_or_create(
        name="Paystack charge",
        defaults={"percentage": Decimal("1.98"), "active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_cart_address_accountdetail_order_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paystack charge', max_length=80)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('1.98'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkout charge',
                'verbose_name_plural': 'Checkout charges',
            },
        ),
        migrations.CreateModel(
            name='ShippingRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ShippingTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=150)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='store.shippingregion')),
            ],
            options={
                'ordering': ['region__position', 'region__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('region', 'slug'), name='unique_shipping_town_per_region')],
            },
        ),
        migrations.RunPython(seed_shipping_regions_and_charge, migrations.RunPython.noop),
    ]
