# Generated by Django 5.2.7 on 2026-06-13 09:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_seed_shipping_regions_and_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
