# Generated by Django 5.2.7 on 2026-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_receipt_generated_at_order_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
