# Generated by Django 5.2.7 on 2026-06-13 09:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_receipt_emailed_at_alter_order_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='receipts/'),
        ),
    ]
